table FactShot
	lineageTag: 8f327e65-e200-406f-a368-7f2a3283edb0

	column ShotID
		dataType: string
		lineageTag: 33a51b19-ddd6-477c-aa6b-7d0e60da09be
		summarizeBy: none
		sourceColumn: ShotID

		annotation SummarizationSetBy = Automatic

	column MatchID
		dataType: int64
		formatString: 0
		lineageTag: cb7e0c7f-2267-4eb3-9b80-781f7c8e413e
		summarizeBy: none
		sourceColumn: MatchID

		annotation SummarizationSetBy = Automatic

	column TeamID
		dataType: int64
		formatString: 0
		lineageTag: 863c8134-fd13-47c8-9e10-8e9747bd2bbe
		summarizeBy: none
		sourceColumn: TeamID

		annotation SummarizationSetBy = Automatic

	column ExpectedGoals
		dataType: double
		lineageTag: c1dc7160-19f6-4e32-a4ab-b83d47caa9a7
		summarizeBy: sum
		sourceColumn: ExpectedGoals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShotOutcome
		dataType: string
		lineageTag: f6794674-eaf9-4436-b075-cf0af1e05465
		summarizeBy: none
		sourceColumn: ShotOutcome

		annotation SummarizationSetBy = Automatic

	partition FactShot = m
		mode: import
		source = ```
				let
				    SelectedShots = Table.SelectColumns(
				        StgShots, 
				        {
				            "ShotID", "MatchID", "TeamID", "ExpectedGoals", "ShotOutcome"
				        }
				    ),
				    TypedShots = Table.TransformColumnTypes(
				        SelectedShots, 
				        {
				            {"ShotID", type text}, 
				            {"MatchID", Int64.Type}, 
				            {"TeamID", Int64.Type},
				            {"ExpectedGoals", type number}, 
				            {"ShotOutcome", type text}
				        }
				    ),
				    TeamMatchKeys = Table.SelectColumns(FactTeamMatch, {"MatchID", "TeamID"}),
				    JoinedTeamMatches = Table.NestedJoin(
				        TypedShots, {"MatchID", "TeamID"},
				        TeamMatchKeys, {"MatchID", "TeamID"}, "TeamMatch", JoinKind.LeftOuter),
				    UnresolvedRows = Table.SelectRows(
				        JoinedTeamMatches, each Table.IsEmpty([TeamMatch])),
				    Output =
				        if not Table.IsEmpty(UnresolvedRows) then
				            error "A FactShot team and match pair does not resolve to FactTeamMatch."
				        else TypedShots
				in
				    Output
				    // SelectedShots
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

