table FactTeamMatch
	lineageTag: fa4ef1eb-ead3-45cd-83f6-cee4def13dad

	column MatchID
		dataType: int64
		formatString: 0
		lineageTag: c0c29bfc-35e5-49d0-9bd0-bbc909175266
		summarizeBy: count
		sourceColumn: MatchID

		annotation SummarizationSetBy = Automatic

	column TeamID
		dataType: int64
		formatString: 0
		lineageTag: b84af3ad-49e1-4c6d-9152-82e7cf573054
		summarizeBy: count
		sourceColumn: TeamID

		annotation SummarizationSetBy = Automatic

	column OpponentTeamID
		dataType: int64
		formatString: 0
		lineageTag: a496fae9-8d39-4be0-bec2-c926d12dce88
		summarizeBy: count
		sourceColumn: OpponentTeamID

		annotation SummarizationSetBy = Automatic

	column OpponentTeamName
		dataType: string
		lineageTag: a3ef7751-064c-4779-a55f-2e4433e49d00
		summarizeBy: none
		sourceColumn: OpponentTeamName

		annotation SummarizationSetBy = Automatic

	column IsHome
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26e02d28-671f-466c-b166-7341df614b02
		summarizeBy: none
		sourceColumn: IsHome

		annotation SummarizationSetBy = Automatic

	column GoalsFor
		dataType: int64
		formatString: 0
		lineageTag: 88de26c0-2f3f-42bd-9a8d-8b7f7593be6d
		summarizeBy: sum
		sourceColumn: GoalsFor

		annotation SummarizationSetBy = Automatic

	column GoalsAgainst
		dataType: int64
		formatString: 0
		lineageTag: 2150e849-7591-4027-a50a-bd2470fbbb96
		summarizeBy: sum
		sourceColumn: GoalsAgainst

		annotation SummarizationSetBy = Automatic

	column ScoreLabel
		dataType: string
		lineageTag: 9203e7e2-9ccf-4283-af21-5ecb9573ea51
		summarizeBy: none
		sourceColumn: ScoreLabel

		annotation SummarizationSetBy = Automatic

	partition FactTeamMatch = m
		mode: import
		source = ```
				let
				    HomeBase = Table.RenameColumns(
				        Table.SelectColumns(StgMatches, {
				            "MatchID", "HomeTeamID", "AwayTeamID", "AwayTeamName", "HomeScore", "AwayScore"
				        }),
				        {
				            {"HomeTeamID", "TeamID"}, {"AwayTeamID", "OpponentTeamID"},
				            {"AwayTeamName", "OpponentTeamName"},
				            {"HomeScore", "GoalsFor"}, {"AwayScore", "GoalsAgainst"}
				        }
				    ),
				    HomeWithRole = Table.AddColumn(HomeBase, "IsHome", each true, type logical),
				    HomeRows = Table.AddColumn(
				        HomeWithRole,
				        "ScoreLabel",
				        each Text.From([GoalsFor]) & "–" & Text.From([GoalsAgainst]),
				        type text
				    ),
				    AwayBase = Table.RenameColumns(
				        Table.SelectColumns(StgMatches, {
				            "MatchID", "AwayTeamID", "HomeTeamID", "HomeTeamName", "AwayScore", "HomeScore"
				        }),
				        {
				            {"AwayTeamID", "TeamID"}, {"HomeTeamID", "OpponentTeamID"},
				            {"HomeTeamName", "OpponentTeamName"},
				            {"AwayScore", "GoalsFor"}, {"HomeScore", "GoalsAgainst"}
				        }
				    ),
				    AwayWithRole = Table.AddColumn(AwayBase, "IsHome", each false, type logical),
				    AwayRows = Table.AddColumn(
				        AwayWithRole,
				        "ScoreLabel",
				        each Text.From([GoalsFor]) & "–" & Text.From([GoalsAgainst]),
				        type text
				    ),
				    CombinedFact = Table.Combine({HomeRows, AwayRows}),
				    FactRows = Table.SelectColumns(
				        CombinedFact, {
				            "MatchID", "TeamID", "OpponentTeamID", "OpponentTeamName",
				            "IsHome", "GoalsFor", "GoalsAgainst", "ScoreLabel"
				        }
				    ),
				    TypedFact = Table.TransformColumnTypes(
				        FactRows, 
				        {
				            {"MatchID", Int64.Type}, 
				            {"TeamID", Int64.Type},
				            {"OpponentTeamID", Int64.Type}, 
				            {"OpponentTeamName", type text},
				            {"IsHome", type logical}, 
				            {"GoalsFor", Int64.Type},
				            {"GoalsAgainst", Int64.Type}, 
				            {"ScoreLabel", type text}
				        }
				    )
				in
				    TypedFact
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

